export const clerkAuthAppearance = {
  variables: {
    colorPrimary: 'hsl(224 79% 58%)',
    colorBackground: 'transparent',
    colorText: 'hsl(210 20% 95%)',
    colorTextSecondary: 'rgba(255, 255, 255, 0.55)',
    colorInputBackground: 'rgba(255, 255, 255, 0.06)',
    colorInputText: 'hsl(210 20% 95%)',
    fontFamily: '"Plus Jakarta Sans", "Inter", "Helvetica Neue", Arial, sans-serif',
    borderRadius: '0.95rem',
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full',
    card: 'w-full rounded-[1.8rem] border border-white/[0.14] bg-gradient-to-br from-white/[0.09] to-white/[0.03] px-8 py-8 shadow-[0_0_100px_rgba(37,99,235,0.25)] backdrop-blur-2xl',
    logoBox: 'hidden',
    headerTitle: 'text-2xl font-semibold tracking-tight text-white',
    headerSubtitle: 'text-sm text-white/60',
    socialButtonsBlockButton:
      'rounded-xl border border-white/[0.12] bg-white/[0.05] text-white transition-all hover:bg-white/[0.1] hover:border-white/[0.2]',
    socialButtonsBlockButtonText: 'text-sm font-medium text-white/90',
    socialButtonsBlockButtonArrow: 'text-white/50',
    dividerLine: 'bg-white/[0.1]',
    dividerText: 'text-[0.62rem] uppercase tracking-[0.28em] text-white/40',
    formFieldLabel: 'text-[0.7rem] font-semibold uppercase tracking-[0.2em] text-white/50',
    formFieldInput:
      'mt-2 rounded-xl border border-white/[0.12] bg-white/[0.08] text-white placeholder:text-white/35 focus:border-[hsl(224,79%,58%)] focus:ring-1 focus:ring-[hsl(224,79%,58%)]/40',
    formFieldInputShowPasswordButton: 'text-white/45 hover:text-white/75',
    formFieldInputIcon: 'text-white/45',
    formButtonPrimary:
      'rounded-xl bg-[hsl(224,79%,58%)] px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-[hsl(224,79%,58%)]/35 transition-all hover:bg-[hsl(224,79%,62%)] hover:shadow-[hsl(224,79%,58%)]/50',
    footerActionLink: 'text-[hsl(224,79%,62%)] hover:text-[hsl(224,79%,70%)]',
    footerActionText: 'text-white/45',
    identityPreviewText: 'text-white/85',
    identityPreviewEditButton: 'text-[hsl(224,79%,62%)] hover:text-[hsl(224,79%,70%)]',
    alertText: 'text-red-300',
    alertIcon: 'text-red-300',
    formFieldErrorText: 'text-red-300',
    otpCodeFieldInput: 'border-white/[0.12] bg-white/[0.08] text-white',
    userButtonPopoverCard: 'rounded-2xl border border-white/[0.08] bg-[hsl(220,22%,8%)] text-white shadow-2xl shadow-black/60',
    userButtonPopoverMain: 'bg-transparent text-white',
    userButtonPopoverFooter: 'border-t border-white/[0.08]',
    userButtonPopoverActionButton:
      'text-white/70 hover:bg-white/[0.06] hover:text-white',
    userButtonPopoverActionButtonText: 'text-white/70',
    userButtonPopoverActionButtonIcon: 'text-white/50',
    userButtonPopoverActionButtonLabel: 'text-white/40',
  },
} as const;
