export const clerkAuthAppearance = {
  variables: {
    colorPrimary: 'hsl(192 54% 50%)',
    colorBackground: 'hsl(220 25% 7%)',
    colorText: 'hsl(210 20% 92%)',
    colorTextSecondary: 'rgba(255, 255, 255, 0.55)',
    colorInputBackground: 'rgba(255, 255, 255, 0.04)',
    colorInputText: 'hsl(210 20% 92%)',
    fontFamily: '"Manrope", "Inter", "Helvetica Neue", Arial, sans-serif',
    borderRadius: '0.75rem',
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full',
    card: 'w-full rounded-2xl border border-white/[0.08] bg-[hsl(220,22%,8%)] px-8 py-8 shadow-2xl shadow-black/60 backdrop-blur-sm',
    logoBox: 'hidden',
    headerTitle: 'text-xl font-semibold text-white',
    headerSubtitle: 'text-sm text-white/50',
    socialButtonsBlockButton:
      'rounded-xl border border-white/[0.08] bg-white/[0.04] text-white transition-all hover:bg-white/[0.08] hover:border-white/[0.15]',
    socialButtonsBlockButtonText: 'text-sm font-medium text-white/90',
    socialButtonsBlockButtonArrow: 'text-white/50',
    dividerLine: 'bg-white/[0.08]',
    dividerText: 'text-[0.65rem] uppercase tracking-[0.2em] text-white/40',
    formFieldLabel: 'text-sm font-medium text-white/70',
    formFieldInput:
      'rounded-xl border border-white/[0.1] bg-white/[0.04] text-white placeholder:text-white/30 focus:border-[hsl(192,54%,50%)] focus:ring-1 focus:ring-[hsl(192,54%,50%)]/30',
    formFieldInputShowPasswordButton: 'text-white/40 hover:text-white/70',
    formFieldInputIcon: 'text-white/40',
    formButtonPrimary:
      'rounded-xl bg-[hsl(192,54%,50%)] px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-[hsl(192,54%,50%)]/20 transition-all hover:bg-[hsl(192,54%,55%)] hover:shadow-[hsl(192,54%,50%)]/30',
    footerActionLink: 'text-[hsl(192,54%,50%)] hover:text-[hsl(192,54%,60%)]',
    footerActionText: 'text-white/40',
    identityPreviewText: 'text-white/80',
    identityPreviewEditButton: 'text-[hsl(192,54%,50%)] hover:text-[hsl(192,54%,60%)]',
    alertText: 'text-red-300',
    alertIcon: 'text-red-300',
    formFieldErrorText: 'text-red-300',
    otpCodeFieldInput: 'border-white/[0.1] bg-white/[0.04] text-white',
    userButtonPopoverCard: 'rounded-2xl border border-white/[0.08] bg-[hsl(220,22%,8%)] text-white shadow-2xl shadow-black/60',
    userButtonPopoverMain: 'bg-transparent text-white',
    userButtonPopoverFooter: 'border-t border-white/[0.08]',
    userButtonPopoverActionButton:
      'text-white/70 hover:bg-white/[0.06] hover:text-white',
    userButtonPopoverActionButtonText: 'text-white/70',
    userButtonPopoverActionButtonIcon: 'text-white/50',
    userButtonPopoverActionButtonLabel: 'text-white/40',
  },
} as const;
