export type Surah = {
  number: number;
  name: string;
  nameArabic: string;
  verses: number;
  juz: number[];
  revelationType: 'meccan' | 'medinan';
};

export const surahs: Surah[] = [
  { number: 1, name: "Al-Fatihah", nameArabic: "الفاتحة", verses: 7, juz: [1], revelationType: "meccan" },
  { number: 2, name: "Al-Baqarah", nameArabic: "البقرة", verses: 286, juz: [1, 2, 3], revelationType: "medinan" },
  { number: 3, name: "Ali 'Imran", nameArabic: "آل عمران", verses: 200, juz: [3, 4], revelationType: "medinan" },
  { number: 4, name: "An-Nisa", nameArabic: "النساء", verses: 176, juz: [4, 5, 6], revelationType: "medinan" },
  { number: 5, name: "Al-Ma'idah", nameArabic: "المائدة", verses: 120, juz: [6, 7], revelationType: "medinan" },
  { number: 6, name: "Al-An'am", nameArabic: "الأنعام", verses: 165, juz: [7, 8], revelationType: "meccan" },
  { number: 7, name: "Al-A'raf", nameArabic: "الأعراف", verses: 206, juz: [8, 9], revelationType: "meccan" },
  { number: 8, name: "Al-Anfal", nameArabic: "الأنفال", verses: 75, juz: [9, 10], revelationType: "medinan" },
  { number: 9, name: "At-Tawbah", nameArabic: "التوبة", verses: 129, juz: [10, 11], revelationType: "medinan" },
  { number: 10, name: "Yunus", nameArabic: "يونس", verses: 109, juz: [11], revelationType: "meccan" },
  { number: 11, name: "Hud", nameArabic: "هود", verses: 123, juz: [11, 12], revelationType: "meccan" },
  { number: 12, name: "Yusuf", nameArabic: "يوسف", verses: 111, juz: [12, 13], revelationType: "meccan" },
  { number: 13, name: "Ar-Ra'd", nameArabic: "الرعد", verses: 43, juz: [13], revelationType: "medinan" },
  { number: 14, name: "Ibrahim", nameArabic: "إبراهيم", verses: 52, juz: [13], revelationType: "meccan" },
  { number: 15, name: "Al-Hijr", nameArabic: "الحجر", verses: 99, juz: [14], revelationType: "meccan" },
  { number: 16, name: "An-Nahl", nameArabic: "النحل", verses: 128, juz: [14], revelationType: "meccan" },
  { number: 17, name: "Al-Isra", nameArabic: "الإسراء", verses: 111, juz: [15], revelationType: "meccan" },
  { number: 18, name: "Al-Kahf", nameArabic: "الكهف", verses: 110, juz: [15, 16], revelationType: "meccan" },
  { number: 19, name: "Maryam", nameArabic: "مريم", verses: 98, juz: [16], revelationType: "meccan" },
  { number: 20, name: "Ta-Ha", nameArabic: "طه", verses: 135, juz: [16], revelationType: "meccan" },
  { number: 21, name: "Al-Anbiya", nameArabic: "الأنبياء", verses: 112, juz: [17], revelationType: "meccan" },
  { number: 22, name: "Al-Hajj", nameArabic: "الحج", verses: 78, juz: [17], revelationType: "medinan" },
  { number: 23, name: "Al-Mu'minun", nameArabic: "المؤمنون", verses: 118, juz: [18], revelationType: "meccan" },
  { number: 24, name: "An-Nur", nameArabic: "النور", verses: 64, juz: [18], revelationType: "medinan" },
  { number: 25, name: "Al-Furqan", nameArabic: "الفرقان", verses: 77, juz: [18, 19], revelationType: "meccan" },
  { number: 26, name: "Ash-Shu'ara", nameArabic: "الشعراء", verses: 227, juz: [19], revelationType: "meccan" },
  { number: 27, name: "An-Naml", nameArabic: "النمل", verses: 93, juz: [19, 20], revelationType: "meccan" },
  { number: 28, name: "Al-Qasas", nameArabic: "القصص", verses: 88, juz: [20], revelationType: "meccan" },
  { number: 29, name: "Al-Ankabut", nameArabic: "العنكبوت", verses: 69, juz: [20, 21], revelationType: "meccan" },
  { number: 30, name: "Ar-Rum", nameArabic: "الروم", verses: 60, juz: [21], revelationType: "meccan" },
  { number: 31, name: "Luqman", nameArabic: "لقمان", verses: 34, juz: [21], revelationType: "meccan" },
  { number: 32, name: "As-Sajdah", nameArabic: "السجدة", verses: 30, juz: [21], revelationType: "meccan" },
  { number: 33, name: "Al-Ahzab", nameArabic: "الأحزاب", verses: 73, juz: [21, 22], revelationType: "medinan" },
  { number: 34, name: "Saba", nameArabic: "سبأ", verses: 54, juz: [22], revelationType: "meccan" },
  { number: 35, name: "Fatir", nameArabic: "فاطر", verses: 45, juz: [22], revelationType: "meccan" },
  { number: 36, name: "Ya-Sin", nameArabic: "يس", verses: 83, juz: [22, 23], revelationType: "meccan" },
  { number: 37, name: "As-Saffat", nameArabic: "الصافات", verses: 182, juz: [23], revelationType: "meccan" },
  { number: 38, name: "Sad", nameArabic: "ص", verses: 88, juz: [23], revelationType: "meccan" },
  { number: 39, name: "Az-Zumar", nameArabic: "الزمر", verses: 75, juz: [23, 24], revelationType: "meccan" },
  { number: 40, name: "Ghafir", nameArabic: "غافر", verses: 85, juz: [24], revelationType: "meccan" },
  { number: 41, name: "Fussilat", nameArabic: "فصلت", verses: 54, juz: [24, 25], revelationType: "meccan" },
  { number: 42, name: "Ash-Shura", nameArabic: "الشورى", verses: 53, juz: [25], revelationType: "meccan" },
  { number: 43, name: "Az-Zukhruf", nameArabic: "الزخرف", verses: 89, juz: [25], revelationType: "meccan" },
  { number: 44, name: "Ad-Dukhan", nameArabic: "الدخان", verses: 59, juz: [25], revelationType: "meccan" },
  { number: 45, name: "Al-Jathiyah", nameArabic: "الجاثية", verses: 37, juz: [25], revelationType: "meccan" },
  { number: 46, name: "Al-Ahqaf", nameArabic: "الأحقاف", verses: 35, juz: [26], revelationType: "meccan" },
  { number: 47, name: "Muhammad", nameArabic: "محمد", verses: 38, juz: [26], revelationType: "medinan" },
  { number: 48, name: "Al-Fath", nameArabic: "الفتح", verses: 29, juz: [26], revelationType: "medinan" },
  { number: 49, name: "Al-Hujurat", nameArabic: "الحجرات", verses: 18, juz: [26], revelationType: "medinan" },
  { number: 50, name: "Qaf", nameArabic: "ق", verses: 45, juz: [26], revelationType: "meccan" },
  { number: 51, name: "Adh-Dhariyat", nameArabic: "الذاريات", verses: 60, juz: [26, 27], revelationType: "meccan" },
  { number: 52, name: "At-Tur", nameArabic: "الطور", verses: 49, juz: [27], revelationType: "meccan" },
  { number: 53, name: "An-Najm", nameArabic: "النجم", verses: 62, juz: [27], revelationType: "meccan" },
  { number: 54, name: "Al-Qamar", nameArabic: "القمر", verses: 55, juz: [27], revelationType: "meccan" },
  { number: 55, name: "Ar-Rahman", nameArabic: "الرحمن", verses: 78, juz: [27], revelationType: "medinan" },
  { number: 56, name: "Al-Waqi'ah", nameArabic: "الواقعة", verses: 96, juz: [27], revelationType: "meccan" },
  { number: 57, name: "Al-Hadid", nameArabic: "الحديد", verses: 29, juz: [27], revelationType: "medinan" },
  { number: 58, name: "Al-Mujadila", nameArabic: "المجادلة", verses: 22, juz: [28], revelationType: "medinan" },
  { number: 59, name: "Al-Hashr", nameArabic: "الحشر", verses: 24, juz: [28], revelationType: "medinan" },
  { number: 60, name: "Al-Mumtahanah", nameArabic: "الممتحنة", verses: 13, juz: [28], revelationType: "medinan" },
  { number: 61, name: "As-Saff", nameArabic: "الصف", verses: 14, juz: [28], revelationType: "medinan" },
  { number: 62, name: "Al-Jumu'ah", nameArabic: "الجمعة", verses: 11, juz: [28], revelationType: "medinan" },
  { number: 63, name: "Al-Munafiqun", nameArabic: "المنافقون", verses: 11, juz: [28], revelationType: "medinan" },
  { number: 64, name: "At-Taghabun", nameArabic: "التغابن", verses: 18, juz: [28], revelationType: "medinan" },
  { number: 65, name: "At-Talaq", nameArabic: "الطلاق", verses: 12, juz: [28], revelationType: "medinan" },
  { number: 66, name: "At-Tahrim", nameArabic: "التحريم", verses: 12, juz: [28], revelationType: "medinan" },
  { number: 67, name: "Al-Mulk", nameArabic: "الملك", verses: 30, juz: [29], revelationType: "meccan" },
  { number: 68, name: "Al-Qalam", nameArabic: "القلم", verses: 52, juz: [29], revelationType: "meccan" },
  { number: 69, name: "Al-Haqqah", nameArabic: "الحاقة", verses: 52, juz: [29], revelationType: "meccan" },
  { number: 70, name: "Al-Ma'arij", nameArabic: "المعارج", verses: 44, juz: [29], revelationType: "meccan" },
  { number: 71, name: "Nuh", nameArabic: "نوح", verses: 28, juz: [29], revelationType: "meccan" },
  { number: 72, name: "Al-Jinn", nameArabic: "الجن", verses: 28, juz: [29], revelationType: "meccan" },
  { number: 73, name: "Al-Muzzammil", nameArabic: "المزمل", verses: 20, juz: [29], revelationType: "meccan" },
  { number: 74, name: "Al-Muddaththir", nameArabic: "المدثر", verses: 56, juz: [29], revelationType: "meccan" },
  { number: 75, name: "Al-Qiyamah", nameArabic: "القيامة", verses: 40, juz: [29], revelationType: "meccan" },
  { number: 76, name: "Al-Insan", nameArabic: "الإنسان", verses: 31, juz: [29], revelationType: "medinan" },
  { number: 77, name: "Al-Mursalat", nameArabic: "المرسلات", verses: 50, juz: [29], revelationType: "meccan" },
  { number: 78, name: "An-Naba", nameArabic: "النبأ", verses: 40, juz: [30], revelationType: "meccan" },
  { number: 79, name: "An-Nazi'at", nameArabic: "النازعات", verses: 46, juz: [30], revelationType: "meccan" },
  { number: 80, name: "Abasa", nameArabic: "عبس", verses: 42, juz: [30], revelationType: "meccan" },
  { number: 81, name: "At-Takwir", nameArabic: "التكوير", verses: 29, juz: [30], revelationType: "meccan" },
  { number: 82, name: "Al-Infitar", nameArabic: "الانفطار", verses: 19, juz: [30], revelationType: "meccan" },
  { number: 83, name: "Al-Mutaffifin", nameArabic: "المطففين", verses: 36, juz: [30], revelationType: "meccan" },
  { number: 84, name: "Al-Inshiqaq", nameArabic: "الانشقاق", verses: 25, juz: [30], revelationType: "meccan" },
  { number: 85, name: "Al-Buruj", nameArabic: "البروج", verses: 22, juz: [30], revelationType: "meccan" },
  { number: 86, name: "At-Tariq", nameArabic: "الطارق", verses: 17, juz: [30], revelationType: "meccan" },
  { number: 87, name: "Al-A'la", nameArabic: "الأعلى", verses: 19, juz: [30], revelationType: "meccan" },
  { number: 88, name: "Al-Ghashiyah", nameArabic: "الغاشية", verses: 26, juz: [30], revelationType: "meccan" },
  { number: 89, name: "Al-Fajr", nameArabic: "الفجر", verses: 30, juz: [30], revelationType: "meccan" },
  { number: 90, name: "Al-Balad", nameArabic: "البلد", verses: 20, juz: [30], revelationType: "meccan" },
  { number: 91, name: "Ash-Shams", nameArabic: "الشمس", verses: 15, juz: [30], revelationType: "meccan" },
  { number: 92, name: "Al-Layl", nameArabic: "الليل", verses: 21, juz: [30], revelationType: "meccan" },
  { number: 93, name: "Ad-Duha", nameArabic: "الضحى", verses: 11, juz: [30], revelationType: "meccan" },
  { number: 94, name: "Ash-Sharh", nameArabic: "الشرح", verses: 8, juz: [30], revelationType: "meccan" },
  { number: 95, name: "At-Tin", nameArabic: "التين", verses: 8, juz: [30], revelationType: "meccan" },
  { number: 96, name: "Al-Alaq", nameArabic: "العلق", verses: 19, juz: [30], revelationType: "meccan" },
  { number: 97, name: "Al-Qadr", nameArabic: "القدر", verses: 5, juz: [30], revelationType: "meccan" },
  { number: 98, name: "Al-Bayyinah", nameArabic: "البينة", verses: 8, juz: [30], revelationType: "medinan" },
  { number: 99, name: "Az-Zalzalah", nameArabic: "الزلزلة", verses: 8, juz: [30], revelationType: "medinan" },
  { number: 100, name: "Al-Adiyat", nameArabic: "العاديات", verses: 11, juz: [30], revelationType: "meccan" },
  { number: 101, name: "Al-Qari'ah", nameArabic: "القارعة", verses: 11, juz: [30], revelationType: "meccan" },
  { number: 102, name: "At-Takathur", nameArabic: "التكاثر", verses: 8, juz: [30], revelationType: "meccan" },
  { number: 103, name: "Al-Asr", nameArabic: "العصر", verses: 3, juz: [30], revelationType: "meccan" },
  { number: 104, name: "Al-Humazah", nameArabic: "الهمزة", verses: 9, juz: [30], revelationType: "meccan" },
  { number: 105, name: "Al-Fil", nameArabic: "الفيل", verses: 5, juz: [30], revelationType: "meccan" },
  { number: 106, name: "Quraysh", nameArabic: "قريش", verses: 4, juz: [30], revelationType: "meccan" },
  { number: 107, name: "Al-Ma'un", nameArabic: "الماعون", verses: 7, juz: [30], revelationType: "meccan" },
  { number: 108, name: "Al-Kawthar", nameArabic: "الكوثر", verses: 3, juz: [30], revelationType: "meccan" },
  { number: 109, name: "Al-Kafirun", nameArabic: "الكافرون", verses: 6, juz: [30], revelationType: "meccan" },
  { number: 110, name: "An-Nasr", nameArabic: "النصر", verses: 3, juz: [30], revelationType: "medinan" },
  { number: 111, name: "Al-Masad", nameArabic: "المسد", verses: 5, juz: [30], revelationType: "meccan" },
  { number: 112, name: "Al-Ikhlas", nameArabic: "الإخلاص", verses: 4, juz: [30], revelationType: "meccan" },
  { number: 113, name: "Al-Falaq", nameArabic: "الفلق", verses: 5, juz: [30], revelationType: "meccan" },
  { number: 114, name: "An-Nas", nameArabic: "الناس", verses: 6, juz: [30], revelationType: "medinan" },
];

export const totalJuz = 30;
export const totalSurahs = 114;
export const totalVerses = surahs.reduce((sum, s) => sum + s.verses, 0);

export function getSurahByNumber(num: number): Surah | undefined {
  return surahs.find(s => s.number === num);
}

export function getSurahsByJuz(juzNum: number): Surah[] {
  return surahs.filter(s => s.juz.includes(juzNum));
}
